#!/bin/bash                                                          

#Set directory as arg                                                
D=$1 #Directory passed in                                           
numFiles=0

#If D is not a directory                                             
if [ ! -d "$D" ]
   then
       >&2 echo 'Argument 1 must be a directory'
       exit 1 #Terminate and give an error                         
fi

#If we are given 2 or more operands
if [ ! -z "$2" ]
   then
       >&2 echo 'Too many arguments'
       exit 1
fi

#If given no operands
if [ -z "$1" ]
   then
       D="$PWD" #Set D to .
fi

#If directory is not readable

if [ ! -r "$D" ]
then
    >&2echo "Unable to read directory"
fi

#If given directory's first character is '-'
if [ ${D:0:1} = '-' ]
   then
       >&2 echo "The directory you pass cannot start with '-'"
       exit 1
fi


#If given directory does not have '/', add it
Dlen=${#D}-1
if [ ! ${D:$Dlen:1} = '/' ]
   then	    
      D="$D/"
fi

#Count number of files
#numFiles="$(find $D -type f | wc -l)"
output=0
hits=0
name=""
#iterate through num of files
for i in $D*
do
    #Filename looks like: Ds/former/path/filename
    #We want to get rid of D's path and only keep filename to examine
    output=0
    Dsize=${#D}
    len=${#i}-$Dsize
    name=${i:$Dsize:$len}
    #Now we have just the filename

    hits=0
    hits=$(find $D -maxdepth 1 -iname "$name" | wc -l)

    if [ $hits -gt 1 ]
    then
	output=1
    fi
    
    #If it doesn't meet guidelines
    if [ ${name:0:1} = '-' ]
    then
	output=1
    elif [ ${name:0:1} = '.' ]
    then
	output=1
    elif echo "$name" | grep -Eq '[^A-Z,a-z,.,_,-]' 
    then
	output=1
    fi

    #If a condition was met 
    if [ $output = 1 ]
    then
       echo "$D$name"  
    fi    
done





    
